Update bootstrap

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -79,7 +79,8 @@ check-installed() {
 # Install a local wget binary which supports TLS (the original one
 # installed on the reMarkable does not) in the PATH
 wget-bootstrap() {
-    local wget_remote=https://github.com/UniqueName992/rm2-bootstrap-temp/blob/main/wget_busybox_armv7l_abihf_musl_Linux
+    local wget_remote=http://toltec-dev.org/thirdparty/bin/wget-v1.21.1-1
+    local wget_checksum=c258140f059d16d24503c62c1fdf747ca843fe4ba8fcd464a6e6bda8c3bbb6b5
 
     if [[ ! -x $wget_path ]]; then
         if [[ -e $wget_path ]]; then
@@ -95,6 +96,11 @@ wget-bootstrap() {
 
         if ! wget -q "$wget_remote" --output-document "$wget_path"; then
             log ERROR "Could not fetch wget, make sure you have a stable Wi-Fi connection"
+            exit 1
+        fi
+
+        if ! sha256sum -c <(echo "$wget_checksum  $wget_path") > /dev/null 2>&1; then
+            log ERROR "Invalid checksum for the local wget binary"
             exit 1
         fi
 
@@ -171,13 +177,6 @@ main() {
 
     log "Installing Toltec and Entware"
 
-    log "home dir"
-    ls /home/root
-    log "local dir"
-    ls /home/root/.local/
-    log "bin dir"
-    ls /home/root/.local/bin
-
     # Create bind mount from user directory to /opt
     rm -rf /opt
     add-bind-mount "$toltec_src" "$toltec_dest"
@@ -189,8 +188,8 @@ main() {
     generate-opkg-conf
 
     # Install base Entware packages
-    /opt/bin/opkg update
-    /opt/bin/opkg install entware-opt
+    opkg update
+    opkg install entware-opt
 
     # Fix for multiuser environment
     chmod 777 /opt/tmp
@@ -233,16 +232,16 @@ main() {
     [[ ! -f /opt/bin/wget ]] && additional_packages+=(wget-ssl)
 
     if [[ ${#additional_packages[@]} -gt 0 ]]; then
-        /opt/bin/opkg install "${additional_packages[@]}"
+        opkg install "${additional_packages[@]}"
     fi
 
     if [[ $# -gt 0 ]]; then
-        /opt/bin/opkg install "$@"
+        opkg install "$@"
     fi
 
     # Reinstall toltec-bootstrap to mark its files as managed,
     # to install its dependencies, and to set the user’s PATH
-    /opt/bin/opkg install toltec-bootstrap
+    opkg install toltec-bootstrap
     log "After each system upgrade, run 'toltecctl reenable' to re-enable Toltec"
 }
 
